#!/bin/bash
docker build . -t nebulaci -f ci/Docker
docker run --rm -e "INCLUDE_EXAMPLES=$INCLUDE_EXAMPLES" -e "BOARD=$BOARD" -e "LM_LICENSE_FILE=$LM_LICENSE_FILE" -e "XILINXD_LICENSE_FILE=$XILINXD_LICENSE_FILE" -e "MLRELEASE=$MLRELEASE"  -e "HDLBRANCH=$HDLBRANCH" -v "$(pwd):/work"  -v /root/.Xilinx:/root/.Xilinxro:ro -v /opt/Xilinx:/opt/Xilinx --mac-address="$ADDR" nebulaci /bin/bash -c "cd /work && chmod +x ci/setupDocker.sh && ./ci/setupDocker.sh && '$@'"
