name: Lint

on: [push, pull_request]

jobs:
  Lint:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Set up Python 3.8
        uses: actions/setup-python@v5
        with:
          python-version: 3.8

      - name: Install dependencies
        run: |
          sudo apt-get install -y python3-pip python3-setuptools
          pip install -r requirements_dev.txt
      - name: Lint
        run: |
          pre-commit run --all-files 2> /dev/null
          ec=$?
          git diff -U0 > log.txt && cat log.txt
          exit $ec
