name: Nebula non-HW Test

on: [push, pull_request]

jobs:
  non-HW-Test:
    runs-on: self-hosted

    steps:
      - uses: actions/checkout@v2
      - name: Workaround for setup python
        run: |
          # Hack to get setup-python to work on act
          if [ ! -f "/etc/lsb-release" ] ; then
            echo "DISTRIB_RELEASE=18.04" > /etc/lsb-release
          fi
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install -r requirements.txt
          pip install setuptools wheel twine

      - name: Install nebula
        run: |
          python setup.py build
          python setup.py install
          python -c "import nebula"

      - name: non-HW Test
        run: |
          cd tests
          pytest test_downloader.py test_cli.py -s -v
